import React from 'react';
import { 
  DocumentArrowDownIcon, 
  CheckCircleIcon,
  ClockIcon,
  ScaleIcon 
} from '@heroicons/react/24/outline';

const SummaryCard = ({ summary }) => {
  const handleDownloadSummary = () => {
    const summaryText = `Document Summary\n\n${summary.title}\n\n${summary.keyPoints.map(point => `• ${point}`).join('\n')}\n\nGenerated by LegalEaseAI`;
    
    const blob = new Blob([summaryText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'legal-document-summary.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-primary-100 dark:bg-primary-900 rounded-lg">
            <ScaleIcon className="h-6 w-6 text-primary-600 dark:text-primary-400" />
          </div>
          <h2 className="text-2xl font-bold text-accent-900 dark:text-accent-100">
            Document Summary
          </h2>
        </div>
        
        <button
          onClick={handleDownloadSummary}
          className="btn-secondary flex items-center space-x-2"
        >
          <DocumentArrowDownIcon className="h-5 w-5" />
          <span>Download Summary</span>
        </button>
      </div>

      {/* Summary Title */}
      <div className="mb-6">
        <h3 className="text-xl font-semibold text-accent-900 dark:text-accent-100 mb-2">
          {summary.title}
        </h3>
        <p className="text-accent-600 dark:text-accent-400">
          {summary.description}
        </p>
      </div>

      {/* Key Points */}
      <div className="space-y-4">
        <h4 className="text-lg font-medium text-accent-900 dark:text-accent-100 flex items-center space-x-2">
          <CheckCircleIcon className="h-5 w-5 text-success-500" />
          <span>Key Points</span>
        </h4>
        
        <ul className="space-y-3">
          {summary.keyPoints.map((point, index) => (
            <li key={index} className="flex items-start space-x-3">
              <div className="flex-shrink-0 w-2 h-2 bg-primary-500 rounded-full mt-2"></div>
              <span className="text-accent-700 dark:text-accent-300">{point}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Document Stats */}
      <div className="mt-6 pt-6 border-t border-accent-200 dark:border-accent-700">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="text-center">
            <div className="text-2xl font-bold text-primary-600 dark:text-primary-400">
              {summary.stats.totalClauses}
            </div>
            <div className="text-sm text-accent-600 dark:text-accent-400">Total Clauses</div>
          </div>
          
          <div className="text-center">
            <div className="text-2xl font-bold text-warning-600 dark:text-warning-400">
              {summary.stats.riskyClauses}
            </div>
            <div className="text-sm text-accent-600 dark:text-accent-400">Risk Flags</div>
          </div>
          
          <div className="text-center flex flex-col items-center">
            <div className="flex items-center space-x-1">
              <ClockIcon className="h-5 w-5 text-accent-600 dark:text-accent-400" />
              <span className="text-lg font-bold text-accent-900 dark:text-accent-100">
                {summary.stats.readingTime}
              </span>
            </div>
            <div className="text-sm text-accent-600 dark:text-accent-400">Reading Time</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SummaryCard;